name: Publish package to the Curseforge/Modrinth/GitHub Packages
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@bc72ac9e9d33a38827c042af2d90014ad4250535
      - name: Execute Gradle build
        run: ./gradlew build
      - uses: Kir-Antipov/mc-publish@45765a374ec0602f500df35a9aecbbbf799fb26d
        with:
          modrinth-id: apotheoticcreation
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: 956637
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}